AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  player-stats-l9

  Sample SAM Template for player-stats-l9

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20
    MemorySize: 128

    Tracing: Active
    # You can add LoggingConfig parameters such as the Logformat, Log Group, and SystemLogLevel or ApplicationLogLevel. Learn more here https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-loggingconfig.
    LoggingConfig:
      LogFormat: JSON
  Api:
    TracingEnabled: true
Resources:
  ProccesDataFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: proccesData/
      Handler: app.procces_data
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        FileUploadEvent:
          Type: S3
          Properties:
            Bucket: !Ref FileStorageBucket
            Events: s3:ObjectCreated:*
      Policies:
        - DynamoDBWritePolicy:
            TableName: player-stats-l9
        - S3FullAccessPolicy:
            BucketName: player-files-l9

  PlayerStatsFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: playerStats/
      Handler: app.player_stats
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        PlayerStatsFunction:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /stats/player/{playerFullName}
            Method: get
      Policies:
        - DynamoDBReadPolicy:
            TableName: player-stats-l9

  FileStorageBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: player-files-l9

  PlayerStatsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: player-stats-l9
      AttributeDefinitions:
        - AttributeName: playerName
          AttributeType: S
      KeySchema:
        - AttributeName: playerName
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Ref: ApplicationResourceGroup
      AutoConfigurationEnabled: "true"
